name: Build LaTeX and deploy on GitHub Releases
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions: { }

env:
  PAPER_BASE_NAME: paper-xxxx-venue-topic

jobs:
  success:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install bibtex-ruby

      - name: Generate bibliography
        run: |
          ruby bibtex_prettifier.rb

      - name: Camera Ready
        run: |
          ruby check-acknowledgements.rb ${{ env.PAPER_BASE_NAME }}.tex

      - name: Build peer review paper
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.PAPER_BASE_NAME }}.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape

      - name: Build camera ready paper
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.PAPER_BASE_NAME }}-camera-ready.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape

      - name: Bump version
        id: bump-version
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true

      - name: Get Time
        id: current-time
        run: echo "::set-output name=time::$(date +'%Y-%m-%dT%H%M%S')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ steps.bump-version.outputs.new_tag }}-${{ steps.current-time.outputs.time }}'
          release_name: '${{ steps.bump-version.outputs.new_tag }}-${{ steps.current-time.outputs.time }}'

      - name: Upload Release Asset peer review paper
        id: upload-release-asset-cv
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.PAPER_BASE_NAME }}.pdf
          asset_name: ${{ env.PAPER_BASE_NAME }}.pdf
          asset_content_type: application/pdf

      - name: Upload Release Asset camera ready paper
        id: upload-release-asset-publications
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.PAPER_BASE_NAME }}-camera-ready.pdf
          asset_name: ${{ env.PAPER_BASE_NAME }}-camera-ready.pdf
          asset_content_type: application/pdf
